"""R0 del informe mensual RPA: el informe congelado como dato.

JEJ tiene que emitir cada mes un informe de reportabilidad RPA ante la DGAC
(estándar `JEJ-GRI-SS-INS-096`). Hasta ahora se armaba a mano; el de agosto de
2026 ya se envió y está en `OneDrive/DGAC/INFORMES/Agosto2026/`. La
especificación de la automatización y el mapeo campo→modelo real están en
`SPEC_REPORTE_MENSUAL_RPA.md` y en `apps/reporting/MAPPING.md`.

**Esta app sólo lee el dominio.** No define reglas de negocio ni toca permisos,
aeronaves ni operadores: recolecta lo que ya existe y lo congela.
"""

from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.core.models import BaseModel


class ReportRun(BaseModel):
    """Un informe mensual, congelado como **dato** y no como PDF.

    Es la pieza que hace posible automatizar: el `payload` guarda el JSON del
    período, y el documento se re-renderiza desde ahí. Así un cambio de diseño no
    obliga a recalcular meses pasados, y comparar mes contra mes es una consulta
    sobre JSON en vez de un diff de documentos.

    **Por qué no se extendió `ComplianceSnapshot`**, que era la primera pregunta
    que `MAPPING.md` dejó planteada: ese modelo guarda seis contadores
    documentales en **columnas fijas** (`total`, `valid`, `expired`, `due_7/15/30`)
    por (fecha, faena), y existe para dar **tendencia diaria**. El informe es otra
    cosa: un payload heterogéneo —KPIs de flota, dotación, cobertura por faena,
    brechas, narrativa— emitido una vez al mes y sujeto a aprobación. Meterlo en
    ese modelo obligaría a un JSON colgando de una tabla de contadores, y
    convertiría un registro diario en uno mensual. Lo que sí hará `ReportRun` es
    **leer** snapshots cuando necesite la tendencia: son fuentes, no rivales.

    ⚠️ **El período no es único, y eso corrige una contradicción del SPEC.** Su
    §1.1 pide `unique_together = [("periodo",)]` y su §5.1 dice que `--force`
    *"crea una versión nueva, no sobrescribe"* — las dos cosas no pueden ser
    ciertas. Se resuelve con `(period, revision)`: el informe es un documento
    controlado (la portada del de agosto dice "Revisión 0"), así que las
    revisiones son parte de su naturaleza y no un accidente. Un informe aprobado
    queda inmutable y una corrección nace como revisión siguiente.
    """

    STATUS_DRAFT = "draft"
    STATUS_APPROVED = "approved"
    STATUS_SUPERSEDED = "superseded"
    STATUS_CHOICES = [
        (STATUS_DRAFT, _("Draft")),
        (STATUS_APPROVED, _("Approved")),
        # Una revisión posterior la reemplazó. No se borra: el informe emitido en
        # su momento es evidencia, y en un sistema de cumplimiento lo que se
        # envió tiene que seguir consultable.
        (STATUS_SUPERSEDED, _("Superseded")),
    ]
    # Los estados desde los que ya no se avanza, leído por el mismo criterio que
    # `LV-90` fijó en el resto del proyecto: la lista vive junto a las choices.
    TERMINAL_STATUSES = frozenset({STATUS_SUPERSEDED})

    # La severidad de un hallazgo, en el vocabulario del informe emitido: sus
    # cuatro llevan un cuadrado rojo o ámbar. No se reutilizan los tokens
    # `--sev-*` de la aplicación (`UX-01`) porque el informe tiene su propia
    # paleta de papel: sale firmado hacia la DGAC y no puede depender del tema
    # de quien lo abrió. Ver la cabecera de `report-a4.css`.
    FINDING_CRITICAL = "critical"
    FINDING_WARNING = "warning"
    FINDING_SEVERITIES = frozenset({FINDING_CRITICAL, FINDING_WARNING})
    FINDING_FIELDS = frozenset({"severity", "title", "text"})

    COMPLETENESS_OK = "ok"
    COMPLETENESS_PARTIAL = "partial"
    COMPLETENESS_CHOICES = [
        (COMPLETENESS_OK, _("Complete")),
        (COMPLETENESS_PARTIAL, _("Partial")),
    ]

    # Primer día del mes reportado. `DateField` y no dos enteros: así el orden y
    # los rangos son los del motor de base de datos y no aritmética a mano.
    period = models.DateField(db_index=True, verbose_name=_("Period"))
    revision = models.PositiveIntegerField(
        default=0,
        verbose_name=_("Revision"),
        help_text=_("0 is the first issue of the period; a correction raises it."),
    )
    generated_by = models.CharField(
        max_length=64,
        verbose_name=_("Generated by"),
        help_text=_('"cron" for the scheduled job, or the username.'),
    )
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default=STATUS_DRAFT
    )
    # El JSON del período. Inmutable por convención una vez aprobado: quien
    # corrige emite una revisión nueva.
    payload = models.JSONField(default=dict, blank=True)
    # **Las rutas del payload que quedaron sin dato, guardadas y no recalculadas.**
    # Es la misma lección que `LV-118` dejó en las alertas: el informe tiene que
    # seguir diciendo qué faltaba **cuando se emitió**, no qué falta hoy. Si se
    # recalculara, un informe de agosto mejoraría solo al cargarse los datos en
    # septiembre, y con él desaparecería la evidencia de la brecha que reportó.
    missing_fields = models.JSONField(default=list, blank=True)
    completeness = models.CharField(
        max_length=20, choices=COMPLETENESS_CHOICES, default=COMPLETENESS_PARTIAL
    )
    # **La narrativa: lo único del informe que no sale de la base y no podría.**
    #
    # `LV-227`. Un hallazgo es un **juicio sobre** las cifras —"la renovación
    # debía haber comenzado ya"—, no una consulta; el informe va firmado y quien
    # firma es quien lo escribe. Por eso se guarda y no se genera.
    #
    # Va en el `ReportRun` y no en una tabla aparte porque **es parte del
    # documento**: un informe aprobado tiene que seguir diciendo lo que decía,
    # narrativa incluida, y con la redacción colgando de otro lado se editaría
    # por detrás de un documento ya emitido.
    findings = models.JSONField(default=list, blank=True)
    # La observación del período (página 3 del informe emitido). Un párrafo, no
    # una lista: en el informe de agosto es uno solo, sobre la vigencia otorgada.
    period_note = models.TextField(blank=True, default="")
    approved_at = models.DateTimeField(null=True, blank=True)
    approved_by = models.CharField(max_length=64, blank=True, default="")

    class Meta:
        verbose_name = _("report run")
        verbose_name_plural = _("report runs")
        ordering = ["-period", "-revision"]
        constraints = [
            models.UniqueConstraint(
                fields=["period", "revision"],
                name="reporting_run_period_revision_uniq",
            ),
        ]
        indexes = [
            # La consulta habitual es "el último informe de este período".
            models.Index(fields=["period", "-revision"], name="reporting_run_last_idx"),
        ]

    def __str__(self):
        return f"{self.code} rev. {self.revision}"

    @property
    def code(self):
        """El código del documento, tal como lo lleva el informe emitido.

        El de agosto dice `JEJ-GTE-CT-INF-RPA-2026-08`. Se compone y no se guarda:
        es una función del período, y una columna con lo mismo sería una columna
        que puede discrepar de su propia fecha.
        """
        return f"JEJ-GTE-CT-INF-RPA-{self.period:%Y-%m}"

    def clean(self):
        """`findings` tiene forma, y se comprueba también acá.

        El formulario no es el único camino a esta columna: el admin, un
        `loaddata` y una corrida de datos escriben igual, y un `JSONField` acepta
        cualquier cosa. Una lista mal formada no revienta al guardar — revienta
        al **renderizar el informe**, que es el peor momento posible. Es la regla
        de `AGENTS.md`: validar en el formulario *y* en el modelo.
        """
        super().clean()
        if not isinstance(self.findings, list):
            raise ValidationError({"findings": _("Findings must be a list.")})
        for entry in self.findings:
            if not isinstance(entry, dict) or set(entry) != self.FINDING_FIELDS:
                raise ValidationError(
                    {"findings": _("Each finding needs a severity, title and text.")}
                )
            if entry["severity"] not in self.FINDING_SEVERITIES:
                raise ValidationError({"findings": _("Unknown finding severity.")})

    @property
    def is_editable(self):
        """Un informe aprobado no se toca: se emite una revisión.

        La aprobación es lo que lo convierte en el documento que se envió, y
        reescribirlo dejaría a la DGAC con una copia que ya no existe de este
        lado.
        """
        return self.status == self.STATUS_DRAFT
