# Generated by Django 6.1 on 2026-09-02 12:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('period', models.DateField(db_index=True, verbose_name='Period')),
                ('revision', models.PositiveIntegerField(default=0, help_text='0 is the first issue of the period; a correction raises it.', verbose_name='Revision')),
                ('generated_by', models.CharField(help_text='"cron" for the scheduled job, or the username.', max_length=64, verbose_name='Generated by')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('completeness', models.CharField(choices=[('ok', 'Complete'), ('partial', 'Partial')], default='partial', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'verbose_name': 'report run',
                'verbose_name_plural': 'report runs',
                'ordering': ['-period', '-revision'],
                'indexes': [models.Index(fields=['period', '-revision'], name='reporting_run_last_idx')],
                'constraints': [models.UniqueConstraint(fields=('period', 'revision'), name='reporting_run_period_revision_uniq')],
            },
        ),
    ]
