# Generated by Django 6.1 on 2026-09-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrun',
            name='findings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='period_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
