# Generated by Django 6.1 on 2026-09-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_narrative_findings_and_period_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrun',
            name='actions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
