# Generated by Django 6.1.1 on 2026-09-23 20:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_executive_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('issued_by', models.CharField(max_length=200, verbose_name='Issued by')),
                ('jointly_with', models.CharField(max_length=200, verbose_name='Jointly with')),
                ('standard', models.CharField(max_length=120, verbose_name='Standard')),
                ('addressed_to', models.CharField(max_length=300, verbose_name='Addressed to')),
                ('scope', models.CharField(max_length=200, verbose_name='Scope')),
                ('sources', models.CharField(max_length=200, verbose_name='Sources')),
                ('plan_lede', models.TextField(verbose_name='Plan introduction')),
            ],
            options={
                'verbose_name': 'report template',
                'verbose_name_plural': 'report templates',
            },
        ),
        migrations.CreateModel(
            name='PlanPhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('month', models.DateField(help_text='The phase is the whole month; the day is ignored.', verbose_name='month')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Description')),
                ('close', models.CharField(max_length=300, verbose_name='Closing criterion')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phases', to='reporting.reporttemplate')),
            ],
            options={
                'verbose_name': 'plan phase',
                'verbose_name_plural': 'plan phases',
                'ordering': ['month'],
            },
        ),
        migrations.CreateModel(
            name='ExigibilityRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('label', models.CharField(max_length=200, verbose_name='What is reported')),
                ('emphasis', models.BooleanField(default=False, verbose_name='Emphasised')),
                ('levels', models.JSONField(blank=True, default=dict, verbose_name='Levels')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matrix_rows', to='reporting.reporttemplate')),
            ],
            options={
                'verbose_name': 'requirement row',
                'verbose_name_plural': 'requirement rows',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
