# Generated by Django 6.0.7 on 2026-07-23 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_operationaltenant_tenantmembership_and_more'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aircraft', to='core.operationaltenant'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_centers', to='core.operationaltenant'),
        ),
        migrations.AddField(
            model_name='operator',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operators', to='core.operationaltenant'),
        ),
    ]
