# Generated by Django 6.0.7 on 2026-07-23 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_aircraft_tenant_costcenter_tenant_operator_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='authorized_services',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='basic_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='max_takeoff_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='parachute',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='vlos',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='responsible',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='operator',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='authorizations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='dgac_credential',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='operator',
            name='operator_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='operator',
            name='rut',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aircraft', to='registry.costcenter'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operators', to='registry.costcenter'),
        ),
    ]
