# Generated by Django 6.0.7 on 2026-07-24 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_assignment_planning_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualification',
            options={'verbose_name': 'qualification', 'verbose_name_plural': 'qualifications'},
        ),
    ]
