# Generated by Django 6.0.7 on 2026-07-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_alter_qualification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='vlos',
            field=models.CharField(blank=True, max_length=20, verbose_name='VLOS'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='dgac_credential',
            field=models.CharField(blank=True, max_length=30, verbose_name='DGAC credential'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='employee_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='rut',
            field=models.CharField(blank=True, max_length=20, verbose_name='RUT'),
        ),
    ]
