# Generated by Django 6.0.7 on 2026-07-24 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_alter_aircraft_vlos_alter_operator_dgac_credential_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='responsible_operator',
            field=models.ForeignKey(blank=True, help_text='Recipient of expiry digests for this cost center.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_centers_in_charge', to='registry.operator'),
        ),
    ]
