# Generated by Django 6.0.7 on 2026-07-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_costcenter_responsible_operator'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['start_date', 'end_date'], name='reg_assignment_range_idx'),
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['expiry_date', 'is_active'], name='reg_qualification_exp_idx'),
        ),
    ]
