# Generated by Django 6.0.7 on 2026-07-25 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_review_performance_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraft',
            options={'verbose_name': 'aircraft', 'verbose_name_plural': 'aircraft'},
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'assignment', 'verbose_name_plural': 'assignments'},
        ),
        migrations.AlterModelOptions(
            name='costcenter',
            options={'verbose_name': 'cost center', 'verbose_name_plural': 'cost centers'},
        ),
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name': 'operator', 'verbose_name_plural': 'operators'},
        ),
    ]
