# Generated by Django 6.0.7 on 2026-07-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_registry_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='responsible_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='responsible_contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
