# Generated by Django 6.0.7 on 2026-07-27 19:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_costcenter_responsible_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('purpose', models.CharField(blank=True, max_length=250)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cc_assignments', to='registry.aircraft')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aircraft_assignments', to='registry.costcenter')),
            ],
            options={
                'verbose_name': 'aircraft assignment',
                'verbose_name_plural': 'aircraft assignments',
                'indexes': [models.Index(fields=['cost_center', 'is_active'], name='reg_acassign_cc_idx'), models.Index(fields=['aircraft', 'end_date'], name='reg_acassign_ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='OperatorAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('purpose', models.CharField(blank=True, max_length=250)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operator_assignments', to='registry.costcenter')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cc_assignments', to='registry.operator')),
            ],
            options={
                'verbose_name': 'operator assignment',
                'verbose_name_plural': 'operator assignments',
                'indexes': [models.Index(fields=['cost_center', 'is_active'], name='reg_opassign_cc_idx'), models.Index(fields=['operator', 'end_date'], name='reg_opassign_op_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResourceMovementLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('sequence', models.PositiveBigIntegerField(editable=False)),
                ('resource_kind', models.CharField(choices=[('operator', 'Operator'), ('aircraft', 'Aircraft')], max_length=20)),
                ('resource_id', models.UUIDField()),
                ('movement', models.CharField(choices=[('assigned', 'Assigned'), ('reassigned', 'Reassigned'), ('released', 'Released')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=250)),
                ('changed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='registry.costcenter')),
                ('to_cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='registry.costcenter')),
            ],
            options={
                'verbose_name': 'resource movement',
                'verbose_name_plural': 'resource movements',
                'ordering': ['-sequence'],
                'indexes': [models.Index(fields=['-sequence'], name='reg_movement_seq_idx'), models.Index(fields=['resource_kind', 'resource_id', '-sequence'], name='reg_movement_res_idx')],
            },
        ),
    ]
