# Generated by Django 6.0.7 on 2026-07-27 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_migrate_assignments_to_per_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='current_location',
            field=models.CharField(choices=[('headquarters', 'Headquarters'), ('on_site', 'On site'), ('maintenance', 'In maintenance')], default='headquarters', max_length=20),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='current_site',
            field=models.ForeignKey(blank=True, help_text='The site this aircraft is deployed to, when on site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='registry.costcenter'),
        ),
        migrations.AlterField(
            model_name='resourcemovementlog',
            name='movement',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('reassigned', 'Reassigned'), ('released', 'Released'), ('location_changed', 'Location changed')], max_length=20),
        ),
    ]
