# Generated by Django 6.0.7 on 2026-07-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_aircraft_current_location_aircraft_current_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='basic_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Basic weight (kg)'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='max_takeoff_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Maximum takeoff weight (kg)'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='responsible_contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='External contact email'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='responsible_contact_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='External contact name'),
        ),
    ]
