# Generated by Django 6.0.7 on 2026-07-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0014_alter_aircraft_basic_weight_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftassignment',
            name='purpose',
            field=models.CharField(blank=True, max_length=250, verbose_name='Operation or purpose'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='purpose',
            field=models.CharField(blank=True, max_length=250, verbose_name='Operation or purpose'),
        ),
        migrations.AlterField(
            model_name='operatorassignment',
            name='purpose',
            field=models.CharField(blank=True, max_length=250, verbose_name='Operation or purpose'),
        ),
    ]
