# Generated by Django 6.0.7 on 2026-07-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0015_costcenter_code_cc_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
