# Generated by Django 6.0.7 on 2026-07-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0016_alter_qualification_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
