# Generated by Django 6.0.7 on 2026-07-31 14:55

import apps.core.tenancy
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_auditevent_options_and_more'),
        ('registry', '0018_backfill_default_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='tenant',
            field=models.ForeignKey(default=apps.core.tenancy.get_default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='aircraft', to='core.operationaltenant'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='tenant',
            field=models.ForeignKey(default=apps.core.tenancy.get_default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='cost_centers', to='core.operationaltenant'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='tenant',
            field=models.ForeignKey(default=apps.core.tenancy.get_default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='operators', to='core.operationaltenant'),
        ),
    ]
