# Generated by Django 6.0.7 on 2026-07-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_auditevent_options_and_more'),
        ('registry', '0019_alter_aircraft_tenant_alter_costcenter_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='operator',
            name='employee_id',
            field=models.CharField(max_length=50, verbose_name='Employee ID'),
        ),
        migrations.AddConstraint(
            model_name='costcenter',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='registry_costcenter_tenant_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='operator',
            constraint=models.UniqueConstraint(fields=('tenant', 'employee_id'), name='registry_operator_tenant_employee_uniq'),
        ),
    ]
