# Generated by Django 6.0.7 on 2026-08-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0020_alter_costcenter_code_alter_operator_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='JAC insurance expiry'),
        ),
        migrations.AddField(
            model_name='operator',
            name='credential_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='DGAC credential expiry'),
        ),
    ]
