# Generated by Django 6.0.7 on 2026-08-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0021_dgac_vigencias_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='responsible_contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='external contact email'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='responsible_contact_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='external contact name'),
        ),
    ]
