# Generated by Django 6.0.7 on 2026-08-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0022_alter_costcenter_responsible_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('damaged', 'Damaged'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='active', max_length=20),
        ),
    ]
