# Generated by Django 6.0.7 on 2026-08-07 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0023_alter_aircraft_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Optional. Lets this person see "My work" filtered to them.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_profile', to=settings.AUTH_USER_MODEL, verbose_name='Linked user account'),
        ),
    ]
