# Generated by Django 6.0.7 on 2026-08-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0024_operator_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='contract_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20),
        ),
    ]
