# Generated by Django 6.0.7 on 2026-08-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0028_aircraft_serial_number_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraft",
            name="insurance_status",
            field=models.CharField(
                blank=True,
                choices=[("pending", "Filing in progress"), ("active", "Active")],
                default="active",
                max_length=20,
                verbose_name="Insurance status",
            ),
        ),
    ]
