# Generated by Django 6.0.7 on 2026-08-11 18:42

import apps.core.tenancy
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_auditevent_options_and_more'),
        ('registry', '0029_r57_aircraft_insurance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Serial number')),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('cycle_count', models.PositiveIntegerField(default=0, verbose_name='Cycles')),
                ('health_percent', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Health (%)')),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired')], default='active', max_length=20)),
                ('first_use_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Entered by hand'), ('aerolink', 'Synced from AeroLink')], default='manual', max_length=20)),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Last synced')),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batteries', to='registry.aircraft', verbose_name='Last seen on aircraft')),
                ('tenant', models.ForeignKey(default=apps.core.tenancy.get_default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='batteries', to='core.operationaltenant')),
            ],
            options={
                'verbose_name': 'battery',
                'verbose_name_plural': 'batteries',
                'ordering': ['serial_number'],
                'indexes': [models.Index(fields=['status', 'is_active'], name='reg_battery_status_idx'), models.Index(fields=['serial_number'], name='reg_battery_serial_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('health_percent__isnull', True), ('health_percent__lte', 100), _connector='OR'), name='reg_battery_health_pct_max')],
            },
        ),
    ]
