# Generated by Django 6.0.7 on 2026-08-12 15:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0030_battery'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='max_rmse_xy_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Maximum horizontal RMSE (cm)'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='max_rmse_z_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Maximum vertical RMSE (cm)'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='required_gsd_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Required GSD (cm)'),
        ),
    ]
