# Generated by Django 6.0.7 on 2026-08-21 14:06

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0034_lv81_insurance_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aerodrome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('code', models.CharField(help_text='As SIGO lists it, e.g. SCEL.', max_length=10, unique=True, verbose_name='ICAO code')),
                ('name', models.CharField(max_length=150)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Leave blank if unverified: it will not be used to compute AMC.', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
            ],
            options={
                'verbose_name': 'aerodrome',
                'verbose_name_plural': 'aerodromes',
                'ordering': ['code'],
            },
        ),
    ]
