# Generated by Django 6.0.8 on 2026-08-26 19:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0035_r92_aerodrome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('taken_at', models.DateTimeField(auto_now_add=True, verbose_name='Taken at')),
                ('question_count', models.PositiveIntegerField(verbose_name='Questions')),
                ('correct_count', models.PositiveIntegerField(verbose_name='Correct answers')),
                ('score_percent', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Score (%)')),
                ('passed', models.BooleanField(verbose_name='Passed')),
                ('expires_on', models.DateField(verbose_name='Valid until')),
                ('answers', models.JSONField(default=list, verbose_name='Answers')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_assessments', to='registry.operator', verbose_name='Operator')),
                ('taken_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_assessments_taken', to=settings.AUTH_USER_MODEL, verbose_name='Taken by')),
            ],
            options={
                'verbose_name': 'knowledge assessment',
                'verbose_name_plural': 'knowledge assessments',
                'ordering': ['-taken_at'],
                'indexes': [models.Index(fields=['expires_on', 'is_active'], name='reg_assessment_exp_idx')],
            },
        ),
    ]
