# Generated by Django 6.1 on 2026-08-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0038_operator_given_names_operator_surnames'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgeassessment',
            options={'ordering': ['-taken_at'], 'permissions': [('view_assessment_answers', 'Can see the assessment answer key')], 'verbose_name': 'knowledge assessment', 'verbose_name_plural': 'knowledge assessments'},
        ),
    ]
