# Generated by Django 6.1 on 2026-08-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0039_alter_knowledgeassessment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftassignment',
            name='purpose',
            field=models.CharField(blank=True, choices=[('photogrammetry', 'Photogrammetry Procedure'), ('video', 'Video Procedure'), ('patrol', 'Patrol'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='purpose',
            field=models.CharField(blank=True, choices=[('photogrammetry', 'Photogrammetry Procedure'), ('video', 'Video Procedure'), ('patrol', 'Patrol'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='operatorassignment',
            name='purpose',
            field=models.CharField(blank=True, choices=[('photogrammetry', 'Photogrammetry Procedure'), ('video', 'Video Procedure'), ('patrol', 'Patrol'), ('other', 'Other')], max_length=20),
        ),
    ]
