# Generated by Django 6.1 on 2026-08-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0040_alter_aircraftassignment_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='operates_flights',
            field=models.BooleanField(default=True, help_text='Uncheck for cost centers that only hold equipment and never fly: they stay out of the flight-permit status table.', verbose_name='Flies in this cost center'),
        ),
    ]
