# Generated by Django 6.0.7 on 2026-07-22 19:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbanstage',
            name='status_type',
            field=models.CharField(choices=[('pending', 'Pending'), ('planned', 'Planned'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('review', 'In review'), ('completed', 'Completed'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
        migrations.CreateModel(
            name='KanbanChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='workboard.kanbantask')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='KanbanLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(default='#2EC4B6', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='workboard.kanbanboard')),
            ],
        ),
        migrations.CreateModel(
            name='KanbanTaskLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workboard.kanbanlabel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workboard.kanbantask')),
            ],
        ),
        migrations.AddField(
            model_name='kanbantask',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tasks', through='workboard.KanbanTaskLabel', to='workboard.kanbanlabel'),
        ),
        migrations.AddConstraint(
            model_name='kanbanlabel',
            constraint=models.UniqueConstraint(fields=('board', 'name'), name='unique_board_label_name'),
        ),
        migrations.AddConstraint(
            model_name='kanbantasklabel',
            constraint=models.UniqueConstraint(fields=('task', 'label'), name='unique_task_label'),
        ),
    ]
