# Generated by Django 6.0.7 on 2026-07-22 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_operationaltenant_tenantmembership_and_more'),
        ('workboard', '0003_kanbanboardaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbanboard',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kanban_boards', to='core.operationaltenant'),
        ),
    ]
