# Generated by Django 6.0.7 on 2026-07-23 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_actor(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Task = apps.get_model("workboard", "KanbanTask")
    users = {u.username: u for u in User.objects.all()}
    for row in Task.objects.exclude(created_by="").iterator():
        if row.created_by in users:
            Task.objects.filter(pk=row.pk).update(created_by_user=users[row.created_by])


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0004_kanbanboard_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbantask',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_tasks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_actor, migrations.RunPython.noop),
    ]
