# Generated by Django 6.0.7 on 2026-07-24 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('registry', '0004_assignment_planning_fields'),
        ('workboard', '0006_kanbantask_source_object'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='kanbantask',
            index=models.Index(fields=['board', 'stage', 'order'], name='workboard_task_board_order_idx'),
        ),
    ]
