# Generated by Django 6.0.7 on 2026-07-25 03:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('registry', '0008_review_performance_indexes'),
        ('workboard', '0007_kanbantask_workboard_task_board_order_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='kanbantask',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='workboard_task_source_idx'),
        ),
    ]
