# Generated by Django 6.0.7 on 2026-08-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0008_review_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbanstage',
            name='wip_limit',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional. Warn when this stage holds more active tasks than this number; does not block moving a task in.', null=True, verbose_name='WIP limit'),
        ),
    ]
