# Generated by Django 6.0.7 on 2026-07-24 22:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_operationaltenant_tenantmembership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('command', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(choices=[('ok', 'Completed'), ('error', 'Failed')], default='ok', max_length=10)),
                ('summary', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'job run',
                'verbose_name_plural': 'job runs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['command', '-started_at'], name='core_jobrun_command_9e33ca_idx')],
            },
        ),
    ]
