# Generated by Django 6.0.7 on 2026-07-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jobrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrun',
            name='result',
            field=models.CharField(choices=[('running', 'Running'), ('ok', 'Completed'), ('error', 'Failed')], default='running', max_length=10),
        ),
    ]
