# Generated by Django 6.0.7 on 2026-07-27 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_jobrun_running_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditevent',
            options={'ordering': ['-sequence']},
        ),
        migrations.RemoveIndex(
            model_name='auditevent',
            name='core_audite_created_9a257b_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditevent',
            name='core_audite_actor_i_5b4f87_idx',
        ),
        migrations.AddField(
            model_name='auditevent',
            name='sequence',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['-sequence'], name='core_audite_sequenc_5b095b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor', '-sequence'], name='core_audite_actor_i_b9b9dd_idx'),
        ),
    ]
