# Generated by Django 6.1 on 2026-09-03 18:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_auditevent_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('list_key', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='Name')),
                ('hidden_columns', models.JSONField(blank=True, default=list)),
                ('query', models.CharField(blank=True, max_length=500)),
                ('is_shared', models.BooleanField(default=False, verbose_name='Shared')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'list_key', 'name'), name='unique_list_preference_per_person')],
            },
        ),
    ]
