# Generated by Django 6.0.7 on 2026-07-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_resolved', 'is_active'], name='compliance_alert_open_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['expiry_date', 'is_current_version'], name='compliance_doc_expiry_cur_idx'),
        ),
    ]
