# Generated by Django 6.0.7 on 2026-07-24 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_alter_alert_alert_rule_alter_alert_content_type_and_more'),
        ('workboard', '0007_kanbantask_workboard_task_board_order_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='create_kanban_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='target_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alert_rules', to='workboard.kanbanboard'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='target_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alert_rules', to='workboard.kanbanstage'),
        ),
    ]
