# Generated by Django 6.0.7 on 2026-07-24 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_alertrule_create_kanban_task_alertrule_target_board_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'document', 'verbose_name_plural': 'documents'},
        ),
    ]
