# Generated by Django 6.0.7 on 2026-07-25 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0006_normalize_alert_rule_targets'),
        ('workboard', '0007_kanbantask_workboard_task_board_order_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='resolved_from_stage',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workboard.kanbanstage'),
        ),
    ]
