# Generated by Django 6.0.7 on 2026-07-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0007_alert_resolved_from_stage'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('workboard', '0007_kanbantask_workboard_task_board_order_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['content_type', 'object_id'], name='compliance_alert_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['content_type', 'object_id'], name='compliance_doc_subject_idx'),
        ),
    ]
