# Generated by Django 6.0.7 on 2026-07-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0008_review_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='is_insurance',
            field=models.BooleanField(default=False, help_text="Shows this type's expiry on the aircraft list (e.g. liability insurance).", verbose_name='Insurance document type'),
        ),
    ]
