# Generated by Django 6.0.7 on 2026-07-27 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0008_review_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compliance.documenttype', verbose_name='Document type'),
        ),
    ]
