# Generated by Django 6.0.7 on 2026-07-31 15:06

import apps.core.tenancy
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0009_documenttype_is_insurance'),
        ('core', '0007_alter_auditevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='tenant',
            field=models.ForeignKey(default=apps.core.tenancy.get_default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='alert_rules', to='core.operationaltenant'),
        ),
        migrations.AddField(
            model_name='document',
            name='tenant',
            field=models.ForeignKey(default=apps.core.tenancy.get_default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.operationaltenant'),
        ),
    ]
