# Generated by Django 6.0.7 on 2026-08-03 18:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0010_alertrule_tenant_document_tenant'),
        ('registry', '0021_dgac_vigencias_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='is_operational_record',
            field=models.BooleanField(default=False, help_text='A per-flight record (flight log, checklist, inspection) tracked in the operational-records repository and the monthly review.', verbose_name='Operational record type'),
        ),
        migrations.CreateModel(
            name='MonthlyComplianceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('period', models.DateField(verbose_name='Period (month)')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('completed', 'Compliant'), ('non_compliant', 'Non-compliant')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_reviews', to='registry.costcenter')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'monthly compliance review',
                'verbose_name_plural': 'monthly compliance reviews',
                'ordering': ['-period', 'cost_center__code'],
                'constraints': [models.UniqueConstraint(fields=('cost_center', 'period'), name='compliance_monthlyreview_cc_period_uniq')],
            },
        ),
    ]
