# Generated by Django 6.0.7 on 2026-08-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0011_operational_records_and_monthly_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="document",
            name="source_reference",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
