# Generated by Django 6.0.7 on 2026-08-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0012_r4_document_provenance"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="resolution_reason",
            field=models.TextField(blank=True),
        ),
    ]
