# Generated by Django 6.0.7 on 2026-08-11 19:56

import apps.core.tenancy
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0013_r62_alert_resolution_reason'),
        ('core', '0007_alter_auditevent_options_and_more'),
        ('registry', '0030_battery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField(verbose_name='Snapshot date')),
                ('total', models.PositiveIntegerField(default=0)),
                ('valid', models.PositiveIntegerField(default=0)),
                ('expired', models.PositiveIntegerField(default=0)),
                ('due_7', models.PositiveIntegerField(default=0)),
                ('due_15', models.PositiveIntegerField(default=0)),
                ('due_30', models.PositiveIntegerField(default=0)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_snapshots', to='registry.costcenter')),
                ('tenant', models.ForeignKey(default=apps.core.tenancy.get_default_tenant, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_snapshots', to='core.operationaltenant')),
            ],
            options={
                'verbose_name': 'compliance snapshot',
                'verbose_name_plural': 'compliance snapshots',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['cost_center', '-date'], name='compliance_snap_trend_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cost_center__isnull', False)), fields=('tenant', 'date', 'cost_center'), name='compliance_snapshot_cc_date_uniq'), models.UniqueConstraint(condition=models.Q(('cost_center__isnull', True)), fields=('tenant', 'date'), name='compliance_snapshot_total_date_uniq')],
            },
        ),
    ]
