# Generated by Django 6.0.7 on 2026-08-12 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0014_r77_compliance_snapshot'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('workboard', '0009_kanbanstage_wip_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='effectiveness_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='effectiveness_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='effectiveness_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='effectiveness_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['effectiveness_due_date', 'effectiveness_verified_at'], name='compliance_alert_effect_idx'),
        ),
    ]
