# Generated by Django 6.0.7 on 2026-08-12 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0015_alert_effectiveness_verification'),
        ('operations', '0016_flightpermission_structured_location'),
        ('registry', '0031_r74_deliverable_quality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('released', 'Released'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('gsd_achieved_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rmse_xy_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rmse_z_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('gcp_count', models.PositiveIntegerField(blank=True, null=True)),
                ('checkpoint_count', models.PositiveIntegerField(blank=True, null=True)),
                ('coverage_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overlap_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('applied_required_gsd_cm', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True)),
                ('applied_max_rmse_xy_cm', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True)),
                ('applied_max_rmse_z_cm', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True)),
                ('release_waiver_reason', models.TextField(blank=True)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliverables', to='registry.costcenter')),
                ('flight_permissions', models.ManyToManyField(blank=True, related_name='deliverables', to='operations.flightpermission')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'deliverable',
                'verbose_name_plural': 'deliverables',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cost_center', 'status'], name='compliance_deliv_cc_idx')],
            },
        ),
    ]
