# Generated by Django 6.0.7 on 2026-08-12 16:46

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0016_r74_deliverable_quality'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('registry', '0031_r74_deliverable_quality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NonConformity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('effectiveness_due_date', models.DateField(blank=True, null=True)),
                ('effectiveness_verified_at', models.DateTimeField(blank=True, null=True)),
                ('effectiveness_note', models.TextField(blank=True)),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('reflight', 'Reflight'), ('rejected_deliverable', 'Rejected deliverable'), ('incident', 'Incident'), ('audit_finding', 'Audit finding')], max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField()),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('detected_on', models.DateField(default=datetime.date.today)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reported_to_dgac_at', models.DateField(blank=True, null=True)),
                ('dgac_report_reference', models.CharField(blank=True, max_length=100)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='non_conformities', to='registry.costcenter')),
                ('effectiveness_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'non-conformity',
                'verbose_name_plural': 'non-conformities',
                'ordering': ['-detected_on', '-created_at'],
                'indexes': [models.Index(fields=['status', 'source'], name='compliance_nc_status_idx'), models.Index(fields=['content_type', 'object_id'], name='compliance_nc_origin_idx')],
            },
        ),
    ]
