# Generated by Django 6.0.7 on 2026-08-13 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0017_r76_non_conformity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'verbose_name': 'alert', 'verbose_name_plural': 'alerts'},
        ),
        migrations.AlterModelOptions(
            name='alertrule',
            options={'verbose_name': 'alert rule', 'verbose_name_plural': 'alert rules'},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name': 'document type', 'verbose_name_plural': 'document types'},
        ),
    ]
