# Generated by Django 6.0.7 on 2026-08-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0020_lv111_alert_watched_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['is_resolved', 'triggered_at'], 'verbose_name': 'alert', 'verbose_name_plural': 'alerts'},
        ),
    ]
