# Generated by Django 6.0.7 on 2026-08-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0021_lv112_alert_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformity',
            name='root_cause_category',
            field=models.CharField(choices=[('undetermined', 'Not yet determined'), ('person', 'Person or competence'), ('procedure', 'Procedure or instruction'), ('equipment', 'Equipment or tooling'), ('material', 'Material or supply'), ('environment', 'Environment or conditions'), ('planning', 'Planning or management'), ('information', 'Information or data')], default='undetermined', max_length=20),
        ),
        migrations.AlterField(
            model_name='nonconformity',
            name='source',
            field=models.CharField(choices=[('reflight', 'Reflight'), ('rejected_deliverable', 'Rejected deliverable'), ('client_complaint', 'Client complaint'), ('incident', 'Incident or accident'), ('equipment_failure', 'Equipment failure'), ('procedure_deviation', 'Procedure deviation'), ('expired_document', 'Expired or missing document'), ('field_observation', 'Field observation'), ('audit_finding', 'Audit finding'), ('external_condition', 'External condition')], max_length=30),
        ),
    ]
