# Generated by Django 6.0.7 on 2026-07-24 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenancehistory_changed_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancehistory',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='maintenance.maintenancerecord'),
        ),
    ]
