# Generated by Django 6.0.7 on 2026-07-24 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_maintenancehistory_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerecord',
            options={'verbose_name': 'maintenance record', 'verbose_name_plural': 'maintenance records'},
        ),
    ]
