# Generated by Django 6.0.7 on 2026-07-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_maintenancerecord_options'),
        ('registry', '0008_review_performance_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['scheduled_date', 'is_active'], name='maint_record_date_idx'),
        ),
    ]
