# Generated by Django 6.0.7 on 2026-07-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_review_performance_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='cost',
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='maintenance_type',
            field=models.CharField(choices=[('to_be_defined', 'To be defined'), ('scheduled', 'Scheduled'), ('unscheduled', 'Unscheduled'), ('emergency', 'Emergency')], max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='performed_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
