# Generated by Django 6.0.7 on 2026-08-13 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_lv82_history_ordering_and_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancehistory',
            name='changed_at',
        ),
    ]
