# Generated by Django 6.0.7 on 2026-07-14 22:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('permission_number', models.CharField(max_length=50, unique=True)),
                ('purpose', models.CharField(max_length=250)),
                ('flight_date', models.DateField()),
                ('location', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('denied', 'Denied'), ('completed', 'Completed')], default='requested', max_length=20)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.aircraft')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.costcenter')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.operator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlightRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('actual_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_records', to='registry.aircraft')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='operations.flightpermission')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.operator')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
