# Generated by Django 6.0.7 on 2026-07-15 13:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_by', models.CharField(max_length=150)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='operations.flightpermission')),
            ],
            options={
                'verbose_name_plural': 'Permission histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
