# Generated by Django 6.0.7 on 2026-07-15 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_permissionhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionhistory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Permission histories'},
        ),
        migrations.RemoveField(
            model_name='permissionhistory',
            name='changed_at',
        ),
    ]
