# Generated by Django 6.0.7 on 2026-07-23 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_actor(apps, schema_editor):
    User = apps.get_model("auth", "User")
    History = apps.get_model("operations", "PermissionHistory")
    users = {u.username: u for u in User.objects.all()}
    for row in History.objects.exclude(changed_by="").iterator():
        if row.changed_by in users:
            History.objects.filter(pk=row.pk).update(changed_by_user=users[row.changed_by])


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_permissionhistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionhistory',
            name='changed_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_history_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_actor, migrations.RunPython.noop),
    ]
