# Generated by Django 6.0.7 on 2026-07-24 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_alter_permissionhistory_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightpermission',
            options={'verbose_name': 'flight permission', 'verbose_name_plural': 'flight permissions'},
        ),
    ]
