# Generated by Django 6.0.7 on 2026-07-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_alter_flightpermission_options'),
        ('registry', '0008_review_performance_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='flightpermission',
            index=models.Index(fields=['flight_date', 'is_active'], name='ops_permission_date_idx'),
        ),
        migrations.AddIndex(
            model_name='flightrecord',
            index=models.Index(fields=['actual_date', 'is_active'], name='ops_record_date_idx'),
        ),
    ]
