# Generated by Django 6.0.7 on 2026-07-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_review_performance_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionhistory',
            options={'ordering': ['-sequence'], 'verbose_name_plural': 'Permission histories'},
        ),
        migrations.AddField(
            model_name='permissionhistory',
            name='sequence',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
