# Generated by Django 6.0.7 on 2026-07-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_alter_permissionhistory_options_and_more'),
        ('registry', '0013_aircraft_current_location_aircraft_current_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightpermission',
            name='aircraft_fleet',
            field=models.ManyToManyField(related_name='flight_permissions', to='registry.aircraft'),
        ),
        migrations.AddField(
            model_name='flightpermission',
            name='operators',
            field=models.ManyToManyField(related_name='flight_permissions', to='registry.operator'),
        ),
        migrations.AddField(
            model_name='flightpermission',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightpermission',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
