# Generated by Django 6.0.7 on 2026-08-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_flightpermission_dgac_mirror_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightpermission',
            name='permission_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
