# Generated by Django 6.0.7 on 2026-07-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_flightpermission_area_name_flightpermission_commune_and_more'),
        ('registry', '0015_alter_aircraftassignment_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightpermission',
            name='aircraft_fleet',
            field=models.ManyToManyField(related_name='flight_permissions', to='registry.aircraft', verbose_name='Aircraft fleet'),
        ),
        migrations.AlterField(
            model_name='flightpermission',
            name='permission_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Permission number'),
        ),
        migrations.AlterField(
            model_name='flightpermission',
            name='valid_from',
            field=models.DateField(verbose_name='Valid from'),
        ),
        migrations.AlterField(
            model_name='flightpermission',
            name='valid_until',
            field=models.DateField(verbose_name='Valid until'),
        ),
    ]
