# Generated by Django 6.0.7 on 2026-08-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_flightpermission_number_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionhistory',
            name='new_status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('denied', 'Denied'), ('completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='permissionhistory',
            name='previous_status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('denied', 'Denied'), ('completed', 'Completed')], max_length=20),
        ),
    ]
