# Generated by Django 6.0.7 on 2026-08-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_alter_permissionhistory_new_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightpermission',
            name='area_type',
            field=models.CharField(choices=[('populated', 'Populated area'), ('unpopulated', 'Unpopulated area'), ('mixed', 'Mixed (crosses both)')], max_length=20, null=True),
        ),
    ]
