# Generated by Django 6.0.7 on 2026-08-12 12:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_flightpermission_purpose_closed_vocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightpermission',
            name='area_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='flightpermission',
            name='commune',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='flightpermission',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))]),
        ),
        migrations.AddField(
            model_name='flightpermission',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))]),
        ),
        migrations.AddField(
            model_name='flightpermission',
            name='max_altitude_ft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightpermission',
            name='radius_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='flightpermission',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
