# Generated by Django 6.0.7 on 2026-08-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_flightpermission_structured_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightpermission',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('denied', 'Denied'), ('completed', 'Completed'), ('expired', 'Expired')], default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='permissionhistory',
            name='new_status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('denied', 'Denied'), ('completed', 'Completed'), ('expired', 'Expired')], max_length=20),
        ),
        migrations.AlterField(
            model_name='permissionhistory',
            name='previous_status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('denied', 'Denied'), ('completed', 'Completed'), ('expired', 'Expired')], max_length=20),
        ),
    ]
