# Generated by Django 6.0.7 on 2026-08-13 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_lv83_permit_expired_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightrecord',
            options={'verbose_name': 'flight record', 'verbose_name_plural': 'flight records'},
        ),
    ]
