# Generated by Django 6.0.7 on 2026-08-21 14:11

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_weather_review'),
        ('operations', '0018_lv80_translatable_model_names'),
        ('registry', '0035_r92_aerodrome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'flight objective',
                'verbose_name_plural': 'flight objectives',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkAreaType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('chapter', models.CharField(blank=True, help_text="As SIGO shows it, e.g. 'Capítulo J - DAN 137'.", max_length=60, verbose_name='Regulatory chapter')),
            ],
            options={
                'verbose_name': 'work area type',
                'verbose_name_plural': 'work area types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FlightRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('title', models.CharField(help_text="Usually the section name from the KMZ, e.g. 'Quebrada km 13.760'.", max_length=200)),
                ('request_type', models.CharField(choices=[('unpopulated_area', 'Unpopulated area operation')], default='unpopulated_area', max_length=30)),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('filed', 'Filed in SIGO'), ('linked', 'Linked to permit'), ('closed', 'Closed')], default='prepared', max_length=20)),
                ('commune', models.CharField(blank=True, max_length=100, verbose_name='Commune')),
                ('area_name', models.CharField(blank=True, max_length=200, verbose_name='Area')),
                ('amc_distance_km', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Distance to AMC (km)')),
                ('center_lat', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('center_lon', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('radius_m', models.PositiveIntegerField(blank=True, null=True, verbose_name='Radius (m)')),
                ('altitude_m', models.PositiveIntegerField(blank=True, null=True, verbose_name='Height (m)')),
                ('hour_from', models.TimeField(blank=True, null=True, verbose_name='From (time)')),
                ('hour_to', models.TimeField(blank=True, null=True, verbose_name='To (time)')),
                ('section_content', models.JSONField(blank=True, null=True)),
                ('filed_on', models.DateField(blank=True, help_text='Used to show how long it has been waiting for an answer.', null=True, verbose_name='Filed in SIGO on')),
                ('amc', models.ForeignKey(blank=True, help_text='Proposed by distance; confirm against the AIP chart.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flight_requests', to='registry.aerodrome', verbose_name='Nearest aerodrome (AMC)')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_requests', to='registry.costcenter')),
                ('flight_permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_requests', to='operations.flightpermission')),
                ('source_plan', models.ForeignKey(blank=True, help_text='The multi-circle plan this section was split from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_requests', to='geo.geoplan')),
            ],
            options={
                'verbose_name': 'flight request',
                'verbose_name_plural': 'flight requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlightRequestHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.PositiveBigIntegerField(default=0, editable=False)),
                ('previous_status', models.CharField(choices=[('prepared', 'Prepared'), ('filed', 'Filed in SIGO'), ('linked', 'Linked to permit'), ('closed', 'Closed')], max_length=20)),
                ('new_status', models.CharField(choices=[('prepared', 'Prepared'), ('filed', 'Filed in SIGO'), ('linked', 'Linked to permit'), ('closed', 'Closed')], max_length=20)),
                ('changed_by', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('changed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_request_history_events', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='operations.flightrequest')),
            ],
            options={
                'verbose_name': 'flight request history',
                'verbose_name_plural': 'flight request histories',
                'ordering': ['-sequence'],
            },
        ),
        migrations.CreateModel(
            name='FlightRequestNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('text', models.TextField(verbose_name='Note')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_request_notes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_notes', to='operations.flightrequest')),
            ],
            options={
                'verbose_name': 'flight request note',
                'verbose_name_plural': 'flight request notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlightRequestWorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.flightobjective')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='operations.flightrequest')),
                ('work_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.workareatype')),
            ],
            options={
                'verbose_name': 'work item',
                'verbose_name_plural': 'work items',
            },
        ),
        migrations.AddIndex(
            model_name='flightrequest',
            index=models.Index(fields=['status', 'is_active'], name='ops_request_status_idx'),
        ),
        migrations.AddIndex(
            model_name='flightrequest',
            index=models.Index(fields=['cost_center', 'is_active'], name='ops_request_cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='flightrequestworkitem',
            constraint=models.UniqueConstraint(fields=('request', 'work_area', 'objective'), name='ops_request_workitem_unique'),
        ),
    ]
