# Generated by Django 6.0.8 on 2026-08-24 20:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_r93_work_area_chapter_help'),
        ('registry', '0035_r92_aerodrome'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightpermission',
            name='amc',
            field=models.ForeignKey(blank=True, help_text='Proposed by distance; confirm against the AIP chart.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flight_permissions', to='registry.aerodrome', verbose_name='Nearest aerodrome (AMC)'),
        ),
        migrations.AddField(
            model_name='flightpermission',
            name='amc_distance_km',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Distance to AMC (km)'),
        ),
    ]
