# Generated by Django 6.1 on 2026-08-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_lv137_permit_amc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightpermission',
            name='purpose',
            field=models.CharField(choices=[('photogrammetry', 'Photogrammetry Procedure'), ('video', 'Video Procedure'), ('patrol', 'Patrol'), ('other', 'Other')], max_length=20),
        ),
    ]
