# Generated by Django 6.1 on 2026-09-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0022_alter_flightpermission_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightpermission',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightpermission',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
