# Generated by Django 6.1 on 2026-09-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0023_alter_flightpermission_valid_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightpermission',
            name='validity_override_reason',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Reason for exceeding the maximum validity'),
        ),
    ]
