# Generated by Django 6.1 on 2026-09-07 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0026_location_provenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotamReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('target_date', models.DateField(verbose_name='Date reviewed for')),
                ('outcome', models.CharField(choices=[('none', 'No NOTAM published for the area'), ('not_affected', 'NOTAM published, none affects the operation'), ('affected', 'A NOTAM affects the operation')], max_length=20, verbose_name='Outcome')),
                ('findings', models.TextField(blank=True, verbose_name='What it said')),
                ('consulted_url', models.CharField(blank=True, max_length=500)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notam_reviews', to='operations.flightpermission')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NOTAM review',
                'verbose_name_plural': 'NOTAM reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
