# Generated by Django 6.1 on 2026-09-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0027_notam_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightpermission',
            name='archived_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
