# Generated by Django 6.1 on 2026-09-08 11:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0028_permit_archived_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreflightChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('name', models.CharField(max_length=150)),
                ('model_keywords', models.CharField(blank=True, help_text='Comma-separated words matched against the aircraft model. Leave it empty for a checklist that applies to every aircraft.', max_length=250)),
            ],
            options={
                'verbose_name': 'preflight checklist',
                'verbose_name_plural': 'preflight checklists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PreflightCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('checklist_name', models.CharField(max_length=150)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('flight_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preflight_check', to='operations.flightrecord')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preflight_checks', to=settings.AUTH_USER_MODEL)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='operations.preflightchecklist')),
            ],
            options={
                'verbose_name': 'preflight check',
                'verbose_name_plural': 'preflight checks',
            },
        ),
        migrations.CreateModel(
            name='PreflightAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('text', models.CharField(max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('value', models.CharField(choices=[('pending', 'not answered'), ('ok', 'Conforming'), ('not_ok', 'Not conforming'), ('na', 'Not applicable')], default='pending', max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('preflight_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='operations.preflightcheck')),
            ],
            options={
                'verbose_name': 'preflight answer',
                'verbose_name_plural': 'preflight answers',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PreflightChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('text', models.CharField(max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.preflightchecklist')),
            ],
            options={
                'verbose_name': 'preflight checklist item',
                'verbose_name_plural': 'preflight checklist items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
