# Generated by Django 6.1.1 on 2026-10-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_geoplan_close_reason_geoplan_close_reason_detail'),
        ('operations', '0029_ux29_preflight_checklist'),
        ('registry', '0041_costcenter_operates_flights'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightrequest',
            name='area_modality',
            field=models.CharField(choices=[('center_point', 'Center point'), ('corridor', 'Corridor point'), ('triangle', 'Triangular'), ('quadrilateral', 'Square grid')], default='center_point', max_length=20, verbose_name='Area modality'),
        ),
        migrations.AddField(
            model_name='flightrequest',
            name='vertices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name='flightrequest',
            constraint=models.CheckConstraint(condition=models.Q(('area_modality__in', ['center_point', 'corridor', 'triangle', 'quadrilateral'])), name='ops_request_area_modality_valid'),
        ),
    ]
