# Generated by Django 6.1.1 on 2026-10-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0030_lv278_area_modality'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightrequest',
            name='approx_flight_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Approximate flight time (minutes)'),
        ),
    ]
