# Generated by Django 6.1.1 on 2026-10-07 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0031_lv278_approx_flight_minutes'),
        ('registry', '0041_costcenter_operates_flights'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preflightcheck',
            name='aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preflight_checks', to='registry.aircraft'),
        ),
        migrations.AddField(
            model_name='preflightcheck',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preflight_checks', to='operations.flightpermission'),
        ),
        migrations.AddField(
            model_name='preflightcheck',
            name='planned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preflightcheck',
            name='flight_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preflight_check', to='operations.flightrecord'),
        ),
        migrations.AddConstraint(
            model_name='preflightcheck',
            constraint=models.CheckConstraint(condition=models.Q(('flight_record__isnull', False), models.Q(('aircraft__isnull', False), ('permission__isnull', False)), _connector='OR'), name='ops_preflight_check_has_an_owner'),
        ),
    ]
