# Generated by Django 6.0.7 on 2026-07-27 15:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0008_review_performance_indexes'),
        ('operations', '0007_review_performance_indexes'),
        ('registry', '0010_costcenter_responsible_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('editing', 'Editing'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='geo_plans', to='registry.costcenter')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='geo_plans_created', to=settings.AUTH_USER_MODEL)),
                ('flight_permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_plans', to='operations.flightpermission')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='compliance.document')),
            ],
            options={
                'verbose_name': 'geo plan',
                'verbose_name_plural': 'geo plans',
                'permissions': [('approve_geoplan', 'Can approve geo plan')],
            },
        ),
        migrations.CreateModel(
            name='GeoPlanHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_by', models.CharField(max_length=150)),
                ('changed_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_plan_history_events', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='geo.geoplan')),
            ],
            options={
                'verbose_name': 'geo plan history entry',
                'verbose_name_plural': 'geo plan history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeoPlanVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('content', models.JSONField()),
                ('content_checksum', models.CharField(max_length=64)),
                ('source', models.CharField(choices=[('import', 'Import'), ('editor', 'Editor'), ('restore', 'Restore')], max_length=20)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('feature_count', models.PositiveIntegerField(default=0)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('bbox_west', models.FloatField(blank=True, null=True)),
                ('bbox_south', models.FloatField(blank=True, null=True)),
                ('bbox_east', models.FloatField(blank=True, null=True)),
                ('bbox_north', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='geo_versions_created', to=settings.AUTH_USER_MODEL)),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.geoplanversion')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='geo.geoplan')),
                ('restored_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.geoplanversion')),
            ],
            options={
                'verbose_name': 'geo plan version',
                'verbose_name_plural': 'geo plan versions',
            },
        ),
        migrations.AddField(
            model_name='geoplan',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='geo.geoplanversion'),
        ),
        migrations.AddIndex(
            model_name='geoplanversion',
            index=models.Index(fields=['plan', '-version_number'], name='geo_version_plan_num_idx'),
        ),
        migrations.AddConstraint(
            model_name='geoplanversion',
            constraint=models.UniqueConstraint(fields=('plan', 'version_number'), name='geo_version_unique_number'),
        ),
        migrations.AddConstraint(
            model_name='geoplanversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='geo_version_number_gte_1'),
        ),
        migrations.AddIndex(
            model_name='geoplan',
            index=models.Index(fields=['status', 'is_active'], name='geo_plan_status_idx'),
        ),
        migrations.AddIndex(
            model_name='geoplan',
            index=models.Index(fields=['cost_center', 'is_active'], name='geo_plan_cc_idx'),
        ),
    ]
