# Generated by Django 6.0.7 on 2026-07-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geoplanhistory',
            options={'ordering': ['-sequence'], 'verbose_name': 'geo plan history entry', 'verbose_name_plural': 'geo plan history'},
        ),
        migrations.AddField(
            model_name='geoplanhistory',
            name='sequence',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
