# Generated by Django 6.0.7 on 2026-07-27 21:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_geoplanhistory_options_geoplanhistory_sequence'),
        ('operations', '0010_flightpermission_dgac_mirror_backfill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPlanPermissionLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('sequence', models.PositiveBigIntegerField(default=0, editable=False)),
                ('changed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('new_permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='operations.flightpermission')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_links', to='geo.geoplan')),
                ('previous_permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='operations.flightpermission')),
            ],
            options={
                'verbose_name': 'geo plan permission link',
                'verbose_name_plural': 'geo plan permission links',
                'ordering': ['-sequence'],
            },
        ),
    ]
