# Generated by Django 6.0.7 on 2026-08-12 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_geoplanpermissionlink'),
        ('operations', '0016_flightpermission_structured_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('target_date', models.DateField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('wind_speed_max', models.FloatField(blank=True, null=True)),
                ('wind_gusts_max', models.FloatField(blank=True, null=True)),
                ('precipitation_sum', models.FloatField(blank=True, null=True)),
                ('precipitation_probability_max', models.FloatField(blank=True, null=True)),
                ('units', models.JSONField(blank=True, default=dict)),
                ('flight_permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='operations.flightpermission')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_reviews', to='geo.geoplan')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'weather review',
                'verbose_name_plural': 'weather reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
