# Generated by Django 6.0.8 on 2026-08-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_lv138_plan_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoplan',
            name='close_reason',
            field=models.CharField(blank=True, choices=[('dgac_rejected', 'Rejected by the DGAC'), ('internal_change', 'Internal modification'), ('other', 'Other')], max_length=20, verbose_name='Reason for closing'),
        ),
        migrations.AddField(
            model_name='geoplan',
            name='close_reason_detail',
            field=models.CharField(blank=True, max_length=250, verbose_name='Reason detail'),
        ),
    ]
